apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: a2a

resources:
  - namespace.yaml
  - agent-registry.yaml
  - sample-agents.yaml
  - agent-rbac.yaml

commonLabels:
  app.kubernetes.io/part-of: agent-gateway-platform
  app.kubernetes.io/managed-by: kustomize
