apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - grafana.yaml

configMapGenerator:
  - name: grafana-datasources
    files:
      - datasources.yaml=datasources/datasources.yaml
  - name: grafana-dashboard-provider
    files:
      - dashboards.yaml=dashboards/dashboards.yaml
  - name: grafana-dashboards
    files:
      - ai-gateway-overview.json=dashboards/ai-gateway-overview.json
      - finops-cost-tracking.json=dashboards/finops-cost-tracking.json

generatorOptions:
  disableNameSuffixHash: true
